import Link from "next/link";

const plans = [
  { name: "Free", intro: "Start, edit, and learn the workflow before choosing a paid plan.", points: ["Create editable carousel drafts", "Use public writing tools", "Try platform presets"] },
  { name: "Pro", intro: "For a steady publishing practice with more creation and export options.", points: ["Expanded creation allowance", "Advanced export options", "Reusable Brand Kits"] },
  { name: "Creator", intro: "For creators producing more visual stories and video formats.", points: ["Higher creation allowance", "Carousel-to-video tools", "All advanced export options"] },
] as const;

export default function PricingPage() {
  return <><header className="container row-between" style={{ minHeight: 72 }}><Link href="/" style={{ fontFamily: "var(--font-display)", fontSize: 22, fontWeight: 650 }}>Orincard</Link><nav className="row" aria-label="Public navigation"><Link className="btn btn-ghost" href="/tools">Tools</Link><Link className="btn btn-primary" href="/create">Create a carousel</Link></nav></header><main className="container" style={{ paddingBlock: "clamp(48px, 8vw, 96px)" }}><section style={{ maxWidth: 760 }}><p className="eyebrow">Plans</p><h1>Start free. Join the paid-plan waitlist.</h1><p className="lead" style={{ marginTop: 20 }}>Paid plan pricing, allowances, payment platform, and launch regions are still being finalized. We will publish them only after they are approved.</p></section><section aria-label="Plan overview" style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 16, marginTop: 48 }}>{plans.map((plan, index) => <article className="panel" key={plan.name} style={{ borderColor: index === 1 ? "var(--fg)" : undefined }}><div className="panel-body stack"><p className="eyebrow">{index === 0 ? "Available now" : "In preparation"}</p><h2>{plan.name}</h2><p>{plan.intro}</p><ul style={{ paddingLeft: 20 }}>{plan.points.map((point) => <li key={point}>{point}</li>)}</ul>{index === 0 ? <Link className="btn btn-secondary" href="/create">Start creating</Link> : <Link className="btn btn-primary" href="#waitlist">Join waitlist</Link>}</div></article>)}</section><section id="waitlist" className="panel" style={{ marginTop: 32, background: "var(--sig-yellow)" }}><div className="panel-body stack"><p className="eyebrow">Waitlist status</p><h2>Paid access is not open yet.</h2><p style={{ maxWidth: 680 }}>Waitlist signup is being connected to a provider. No email is collected or stored on this page today. Check back here for an approved signup option.</p><div><Link className="btn btn-primary" href="/">Return home</Link></div></div></section></main></>;
}
