create type public.recovery_import_state as enum ('inspected', 'confirmed', 'expired');
comment on type public.recovery_import_state is '恢复包检查记录生命周期';
create table public.recovery_imports (
  id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete restrict,
  asset_id uuid not null references public.assets(id) on delete restrict, inspection_hash text not null check (inspection_hash ~ '^[0-9a-f]{64}$'),
  document jsonb not null check (jsonb_typeof(document) = 'object'), missing_assets jsonb not null default '[]'::jsonb check (jsonb_typeof(missing_assets) = 'array'),
  state public.recovery_import_state not null default 'inspected', expires_at timestamptz not null, created_at timestamptz not null default now()
);
comment on table public.recovery_imports is '用户私有恢复包检查快照，确认前不创建项目';
comment on column public.recovery_imports.id is '恢复检查唯一标识'; comment on column public.recovery_imports.owner_id is '检查所有者标识'; comment on column public.recovery_imports.asset_id is '已验证恢复包素材标识'; comment on column public.recovery_imports.inspection_hash is '预览与确认比较哈希'; comment on column public.recovery_imports.document is '经校验的恢复项目文档'; comment on column public.recovery_imports.missing_assets is '包中缺失的资源标识'; comment on column public.recovery_imports.state is '检查、确认或过期状态'; comment on column public.recovery_imports.expires_at is '确认有效期截止时间'; comment on column public.recovery_imports.created_at is '检查创建时间（UTC）';
alter table public.recovery_imports enable row level security; revoke all on public.recovery_imports from anon, authenticated; grant select,insert,update,delete on public.recovery_imports to service_role;
create or replace function public.server_confirm_recovery_import(p_owner_id uuid, p_import_id uuid, p_inspected_document jsonb, p_restored_document jsonb) returns jsonb language plpgsql security definer set search_path = '' as $$ declare target public.recovery_imports; created public.projects; begin select * into target from public.recovery_imports where id=p_import_id and owner_id=p_owner_id and state='inspected' for update; if target.id is null or target.expires_at <= now() or target.document <> p_inspected_document then raise exception using errcode='42501', message='recovery inspection unavailable'; end if; created := private.create_project(p_owner_id, p_restored_document->>'title', (p_restored_document->>'platform')::public.platform_preset, p_restored_document); update public.recovery_imports set state='confirmed' where id=target.id; return jsonb_build_object('projectId',created.id,'revision',created.revision); end; $$;
comment on function public.server_confirm_recovery_import(uuid, uuid, jsonb, jsonb) is '校验同所有者未过期的原始检查快照，并以重写资源标识后的恢复快照创建新项目与版本'; revoke execute on function public.server_confirm_recovery_import(uuid, uuid, jsonb, jsonb) from public, anon, authenticated; grant execute on function public.server_confirm_recovery_import(uuid, uuid, jsonb, jsonb) to service_role;
