/**
 * Vendors third-party artwork declared by src/assets/vendor-manifest.json.
 *
 * Nothing here downloads "the latest" of anything: every source is pinned to a commit sha, the
 * archive is checked against a recorded sha256 before it is opened, and each extracted file is
 * checked against its own sha256 before it is read. A source whose licence is not on the
 * attribution-free allowlist is refused outright rather than vendored with a caveat.
 *
 *   node scripts/vendor-assets.mjs                 # verify + regenerate the output modules
 *   node scripts/vendor-assets.mjs --source tabler-icons
 *   node scripts/vendor-assets.mjs --update        # record new hashes after changing a pin
 *
 * Downloads land in .cache/vendor/ and are reused, so a rerun is offline as long as the pin
 * has not moved.
 */
import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";

const run = promisify(execFile);

const ROOT = new URL("../", import.meta.url);
const MANIFEST = new URL("src/assets/vendor-manifest.json", ROOT);
const CACHE_DIR = new URL(".cache/vendor/", ROOT);
const LICENSE_DIR = new URL("docs/licenses/vendor/", ROOT);

const args = process.argv.slice(2);
const UPDATE = args.includes("--update");
const sourceFlag = args.indexOf("--source");
const ONLY = sourceFlag === -1 ? null : args[sourceFlag + 1];

const sha256 = (bytes) => createHash("sha256").update(bytes).digest("hex");

/** Fetch the pinned archive, reusing the cached copy when its bytes still match the manifest. */
async function archiveBytes(source) {
  const cached = new URL(`${source.id}-${source.commit}.tar.gz`, CACHE_DIR);
  try {
    const bytes = await readFile(cached);
    if (sha256(bytes) === source.archiveSha256 || UPDATE) return { bytes, cached, fromCache: true };
  } catch {
    // Not cached yet; fall through to the download.
  }
  const url = `https://codeload.github.com/${source.owner}/${source.repo}/tar.gz/${source.commit}`;
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${source.id}: ${url} returned ${response.status}`);
  const bytes = Buffer.from(await response.arrayBuffer());
  await mkdir(CACHE_DIR, { recursive: true });
  await writeFile(cached, bytes);
  return { bytes, cached, fromCache: false };
}

/**
 * Strip the editorial comment and the <svg> wrapper, keeping the drawing only.
 *
 * The wrapper is regenerated by the renderer so the icon inherits the slide's colour through
 * currentColor and the slide's sizing through the surrounding box. Keeping upstream's fixed
 * width="24" height="24" would pin every icon to 24 CSS pixels inside a 1080px card.
 */
function tablerIcons(source, files) {
  const icons = files.map(({ file, text }) => {
    const variant = file.path.includes("/filled/") ? "filled" : "outline";
    const name = file.path.split("/").pop().replace(/\.svg$/, "");
    const id = variant === "filled" ? `${name}-filled` : name;
    const body = text.match(/<svg[^>]*>([\s\S]*?)<\/svg>/)?.[1];
    if (!body) throw new Error(`${file.path}: no <svg> element`);
    const markup = body.replace(/\s+/g, " ").trim();
    if (!markup.includes("<path") && !markup.includes("<circle")) {
      throw new Error(`${file.path}: no drawing commands`);
    }
    return { id, variant, markup };
  });
  const seen = new Set();
  for (const icon of icons) {
    if (seen.has(icon.id)) throw new Error(`duplicate icon id ${icon.id}`);
    seen.add(icon.id);
  }
  icons.sort((a, b) => a.id.localeCompare(b.id));

  const entries = icons
    .map((icon) => `  "${icon.id}": { variant: "${icon.variant}", markup: ${JSON.stringify(icon.markup)} },`)
    .join("\n");

  return `// Generated by scripts/vendor-assets.mjs from ${source.repository} @ ${source.commit}
// ${source.license} — ${source.copyright}. Do not edit: change src/assets/vendor-manifest.json
// and rerun \`node scripts/vendor-assets.mjs\`.

/** How the drawing expects to be painted. Outline icons are stroked, filled icons are filled. */
export type IconVariant = "outline" | "filled";

export type IconDefinition = {
  variant: IconVariant;
  /** Inner SVG markup, without the <svg> wrapper. Colour comes from currentColor. */
  markup: string;
};

export const ICON_VIEW_BOX = "0 0 24 24";

export const tablerIcons = {
${entries}
} as const satisfies Record<string, IconDefinition>;

export type IconName = keyof typeof tablerIcons;

export const iconNames = Object.keys(tablerIcons) as IconName[];
`;
}

/**
 * Concatenate boring-avatars' generator components into one module.
 *
 * Upstream ships one file per style and every one of them declares its own top-level `SIZE`,
 * `ELEMENTS` and `generateColors`, so a plain concatenation collides on all three. Renaming them
 * would mean editing vendored code by hand; wrapping each file's body in an IIFE keeps the code
 * byte-for-byte what the sha256 covers and gives each style its own scope. The only edits are
 * mechanical: drop the `import` lines (React and the shared helpers are already in scope here) and
 * turn `export default X` into the IIFE's return.
 */
function boringAvatars(source, files) {
  const byPath = new Map(files.map((entry) => [entry.file.path, entry.text]));
  const take = (path) => {
    const text = byPath.get(path);
    if (text === undefined) throw new Error(`${source.id}: ${path} missing from files[]`);
    return text;
  };
  const withoutImports = (text) =>
    text
      .split("\n")
      .filter((line) => !/^import[\s{]/.test(line))
      .join("\n")
      .trim();

  // The helpers stay private: they are an implementation detail of the styles, not our API.
  const utilities = withoutImports(take("src/lib/utilities.ts")).replace(/^export const /gm, "const ");
  const types = withoutImports(take("src/lib/components/types.ts"));

  const styles = [];
  for (const { file, text } of files) {
    const style = file.path.match(/\/avatar-([a-z]+)\.tsx$/)?.[1];
    if (!style) continue;
    const body = withoutImports(text);
    const exported = body.match(/^export default (\w+);?$/m)?.[1];
    if (!exported) throw new Error(`${file.path}: no \`export default <name>\``);
    const inner = body
      .replace(/^export default \w+;?$/m, `return ${exported};`)
      .split("\n")
      .map((line) => (line ? `  ${line}` : line))
      .join("\n");
    styles.push({ style, component: exported, inner });
  }
  if (styles.length === 0) throw new Error(`${source.id}: no avatar-*.tsx in files[]`);
  styles.sort((a, b) => a.style.localeCompare(b.style));

  const blocks = styles
    .map(({ component, inner }) => `const ${component} = (() => {\n${inner}\n})();`)
    .join("\n\n");
  const registry = styles.map(({ style, component }) => `  ${style}: ${component},`).join("\n");

  return `// Generated by scripts/vendor-assets.mjs from ${source.repository} @ ${source.commit}
// ${source.license} — ${source.copyright}. Do not edit: change src/assets/vendor-manifest.json
// and rerun \`node scripts/vendor-assets.mjs\`.

import * as React from "react";
// types.ts imports this; the import lines are stripped, so it has to be re-declared here.
import type { SVGProps } from "react";

${types}

${utilities}

${blocks}

/** Every generative style, keyed the way theme.background.motif spells it. */
export const boringAvatars = {
${registry}
} as const;

export type BoringAvatarStyle = keyof typeof boringAvatars;

export const boringAvatarStyles = Object.keys(boringAvatars) as BoringAvatarStyle[];
`;
}

const TRANSFORMS = { "tabler-icons": tablerIcons, "boring-avatars": boringAvatars };

const manifest = JSON.parse(await readFile(MANIFEST, "utf8"));
const allowed = new Set(manifest.allowedLicenses);
let changed = false;

for (const source of manifest.sources) {
  if (ONLY && source.id !== ONLY) continue;

  // Refuse before downloading: an attribution or copyleft obligation is not something to discover
  // after the bytes are already in the working tree.
  if (!allowed.has(source.license)) {
    throw new Error(`ASSET_LICENSE_REJECTED: ${source.id} is ${source.license}; allowed: ${[...allowed].join(", ")}`);
  }
  if (source.attributionRequired) {
    throw new Error(`ASSET_LICENSE_REJECTED: ${source.id} requires attribution`);
  }
  if (!/^[0-9a-f]{40}$/.test(source.commit)) {
    throw new Error(`${source.id}: commit must be a full 40-character sha, got ${source.commit}`);
  }

  const { bytes, cached, fromCache } = await archiveBytes(source);
  const actual = sha256(bytes);
  if (actual !== source.archiveSha256) {
    if (!UPDATE) {
      throw new Error(`ARCHIVE_HASH_MISMATCH: ${source.id} expected ${source.archiveSha256} but received ${actual}`);
    }
    source.archiveSha256 = actual;
    changed = true;
  }
  process.stdout.write(`${source.id} @ ${source.commit.slice(0, 12)} (${fromCache ? "cached" : "downloaded"} ${(bytes.length / 1e6).toFixed(1)}MB)\n`);

  const workDir = await mkdtemp(join(tmpdir(), `vendor-${source.id}-`));
  try {
    await run("tar", ["xzf", cached.pathname, "-C", workDir]);
    // codeload wraps everything in <repo>-<sha>/.
    const prefix = join(workDir, `${source.repo}-${source.commit}`);

    const files = [];
    const mismatched = [];
    for (const file of source.files) {
      const raw = await readFile(join(prefix, file.path));
      const hash = sha256(raw);
      if (hash !== file.sha256) {
        if (!UPDATE) {
          mismatched.push(`${file.path}: expected ${file.sha256} but received ${hash}`);
          continue;
        }
        file.sha256 = hash;
        changed = true;
      }
      files.push({ file, text: raw.toString("utf8") });
    }
    if (mismatched.length > 0) {
      throw new Error(`ASSET_HASH_MISMATCH in ${source.id}:\n  ${mismatched.join("\n  ")}`);
    }

    // MIT and Apache-2.0 both require the licence text to travel with the copies, and CC0 is
    // clearer with it present, so it ships regardless of which of the allowed licences applies.
    await mkdir(LICENSE_DIR, { recursive: true });
    const licenseText = await readFile(join(prefix, source.licenseFile), "utf8");
    await writeFile(new URL(`${source.id}-LICENSE.txt`, LICENSE_DIR), licenseText);

    const transform = TRANSFORMS[source.transform];
    if (!transform) throw new Error(`${source.id}: unknown transform ${source.transform}`);
    await writeFile(new URL(source.output, ROOT), transform(source, files));
    process.stdout.write(`  ${source.files.length} files -> ${source.output}\n`);
  } finally {
    await rm(workDir, { recursive: true, force: true });
  }
}

if (changed) {
  await writeFile(MANIFEST, `${JSON.stringify(manifest, null, 2)}\n`);
  process.stdout.write("updated src/assets/vendor-manifest.json\n");
}
