-- Generated by scripts/prepare-migrations.mjs. Do not edit by hand.
-- T016-T019 walking skeleton database baseline.

-- source: supabase/definitions/identity.sql
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_type
    where typnamespace = 'public'::regnamespace
      and typname = 'account_status'
  ) then
    create type public.account_status as enum ('active', 'deleting', 'deleted');
  end if;
end
$$;

comment on type public.account_status is '账户访问与删除流程状态';

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete restrict,
  display_name text,
  preferences jsonb not null default '{}'::jsonb,
  status public.account_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.profiles is '用户公开工作区配置与账户访问状态';
comment on column public.profiles.id is '用户唯一标识，与认证主体一致';
comment on column public.profiles.display_name is '用户显示名称';
comment on column public.profiles.preferences is '默认语言、语气、页数和生成指令，不含权益';
comment on column public.profiles.status is '账户访问及删除流程状态';
comment on column public.profiles.created_at is '创建时间（UTC）';
comment on column public.profiles.updated_at is '最近修改时间（UTC）';

create or replace function private.create_profile_for_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id) values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

comment on function private.create_profile_for_auth_user() is '为新认证主体建立最小工作区资料';
revoke execute on function private.create_profile_for_auth_user() from public, anon, authenticated;

drop trigger if exists create_profile_after_auth_user on auth.users;
create trigger create_profile_after_auth_user
after insert on auth.users
for each row execute function private.create_profile_for_auth_user();

create or replace function private.set_profile_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

comment on function private.set_profile_updated_at() is '在资料修改时记录最近修改时间';
revoke execute on function private.set_profile_updated_at() from public, anon, authenticated;

drop trigger if exists set_profile_updated_at on public.profiles;
create trigger set_profile_updated_at
before update on public.profiles
for each row execute function private.set_profile_updated_at();

alter table public.profiles enable row level security;

revoke all on table public.profiles from anon, authenticated, service_role;
grant select on table public.profiles to authenticated;
grant update (display_name, preferences) on table public.profiles to authenticated;
grant select, update on table public.profiles to service_role;

drop policy if exists profiles_select_own_active on public.profiles;
create policy profiles_select_own_active
on public.profiles
for select
to authenticated
using ((select auth.uid()) = id and status = 'active');

drop policy if exists profiles_update_own_active on public.profiles;
create policy profiles_update_own_active
on public.profiles
for update
to authenticated
using ((select auth.uid()) = id and status = 'active')
with check ((select auth.uid()) = id and status = 'active');

-- source: supabase/definitions/projects.sql
do $$
begin
  if not exists (
    select 1 from pg_type
    where typnamespace = 'public'::regnamespace and typname = 'platform_preset'
  ) then
    create type public.platform_preset as enum ('linkedin', 'instagram', 'tiktok');
  end if;
  if not exists (
    select 1 from pg_type
    where typnamespace = 'public'::regnamespace and typname = 'project_state'
  ) then
    create type public.project_state as enum ('draft', 'archived', 'deleting', 'deleted');
  end if;
  if not exists (
    select 1 from pg_type
    where typnamespace = 'public'::regnamespace and typname = 'project_version_reason'
  ) then
    create type public.project_version_reason as enum ('manual', 'pre_generation', 'export', 'restore');
  end if;
end
$$;

comment on type public.platform_preset is '受控的社交平台画布预设';
comment on type public.project_state is '项目生命周期状态';
comment on type public.project_version_reason is '不可变项目快照的建立原因';

grant usage on schema private to service_role;

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users (id) on delete restrict,
  title text not null check (length(btrim(title)) between 1 and 200),
  platform public.platform_preset not null,
  document jsonb not null check (jsonb_typeof(document) = 'object'),
  revision bigint not null default 1 check (revision >= 1),
  brand_kit_id uuid,
  state public.project_state not null default 'draft',
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint projects_document_identity_check check (
    document @> '{"schemaVersion": 1}'::jsonb
    and document ->> 'title' = title
    and document ->> 'platform' = platform::text
  ),
  constraint projects_deleted_state_check check (
    (state in ('deleting', 'deleted') and deleted_at is not null)
    or (state in ('draft', 'archived') and deleted_at is null)
  )
);

comment on table public.projects is '私有轮播当前稿';
comment on column public.projects.id is '项目唯一标识';
comment on column public.projects.owner_id is '项目所有者标识';
comment on column public.projects.title is '项目库显示标题，与文档标题事务内同步';
comment on column public.projects.platform is '当前输出平台预设';
comment on column public.projects.document is 'CarouselDocument 当前内容，不含原始文件字节';
comment on column public.projects.revision is '乐观并发控制版本';
comment on column public.projects.brand_kit_id is '当前关联品牌标识，删除品牌后可解除但保留文档快照';
comment on column public.projects.state is '项目生命周期状态';
comment on column public.projects.deleted_at is '逻辑删除时间，设置后立即影响授权';
comment on column public.projects.created_at is '创建时间（UTC）';
comment on column public.projects.updated_at is '最近修改时间（UTC）';

create table if not exists public.project_versions (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete restrict,
  owner_id uuid not null references auth.users (id) on delete restrict,
  revision bigint not null check (revision >= 1),
  document jsonb not null check (jsonb_typeof(document) = 'object'),
  reason public.project_version_reason not null,
  created_at timestamptz not null default now(),
  unique (project_id, revision)
);

comment on table public.project_versions is '不可变项目快照';
comment on column public.project_versions.id is '版本记录唯一标识';
comment on column public.project_versions.project_id is '所属项目标识';
comment on column public.project_versions.owner_id is '项目所有者标识';
comment on column public.project_versions.revision is '所保存的编辑版本';
comment on column public.project_versions.document is '该版本的完整 CarouselDocument 快照';
comment on column public.project_versions.reason is '建立快照的业务原因';
comment on column public.project_versions.created_at is '快照创建时间（UTC）';

create index if not exists projects_owner_state_updated_idx
on public.projects (owner_id, state, updated_at desc);
create index if not exists project_versions_owner_created_idx
on public.project_versions (owner_id, created_at desc);
create index if not exists project_versions_project_id_idx
on public.project_versions (project_id);

create or replace function private.reject_project_version_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception using errcode = '55000', message = 'project versions are immutable';
end;
$$;

comment on function private.reject_project_version_mutation() is '阻止历史项目快照被更新或删除';
revoke execute on function private.reject_project_version_mutation() from public, anon, authenticated, service_role;

drop trigger if exists project_versions_are_immutable on public.project_versions;
create trigger project_versions_are_immutable
before update or delete on public.project_versions
for each row execute function private.reject_project_version_mutation();

create or replace function private.create_project(
  p_owner_id uuid,
  p_title text,
  p_platform public.platform_preset,
  p_document jsonb
)
returns public.projects
language plpgsql
security definer
set search_path = ''
as $$
declare
  created_project public.projects;
begin
  if not exists (
    select 1 from public.profiles
    where id = p_owner_id and status = 'active'
  ) then
    raise exception using errcode = '42501', message = 'account is not active';
  end if;

  insert into public.projects (owner_id, title, platform, document)
  values (p_owner_id, p_title, p_platform, p_document)
  returning * into created_project;

  insert into public.project_versions (project_id, owner_id, revision, document, reason)
  values (created_project.id, p_owner_id, 1, p_document, 'manual');

  return created_project;
end;
$$;

comment on function private.create_project(uuid, text, public.platform_preset, jsonb) is '为已验证的活跃账户创建项目及首个不可变快照';
revoke execute on function private.create_project(uuid, text, public.platform_preset, jsonb) from public, anon, authenticated;
grant execute on function private.create_project(uuid, text, public.platform_preset, jsonb) to service_role;

create or replace function private.save_project(
  p_owner_id uuid,
  p_project_id uuid,
  p_expected_revision bigint,
  p_title text,
  p_platform public.platform_preset,
  p_document jsonb,
  p_reason public.project_version_reason default 'manual'
)
returns public.projects
language plpgsql
security definer
set search_path = ''
as $$
declare
  saved_project public.projects;
begin
  if not exists (
    select 1 from public.profiles
    where id = p_owner_id and status = 'active'
  ) then
    raise exception using errcode = '42501', message = 'account is not active';
  end if;

  update public.projects
  set title = p_title,
      platform = p_platform,
      document = p_document,
      revision = revision + 1,
      updated_at = now()
  where id = p_project_id
    and owner_id = p_owner_id
    and state in ('draft', 'archived')
    and revision = p_expected_revision
  returning * into saved_project;

  if saved_project.id is null then
    raise exception using errcode = '40001', message = 'project revision conflict';
  end if;

  insert into public.project_versions (project_id, owner_id, revision, document, reason)
  values (
    saved_project.id,
    saved_project.owner_id,
    saved_project.revision,
    saved_project.document,
    p_reason
  );

  return saved_project;
end;
$$;

comment on function private.save_project(uuid, uuid, bigint, text, public.platform_preset, jsonb, public.project_version_reason) is '以 expected revision 比较交换保存项目并建立不可变快照';
revoke execute on function private.save_project(uuid, uuid, bigint, text, public.platform_preset, jsonb, public.project_version_reason) from public, anon, authenticated;
grant execute on function private.save_project(uuid, uuid, bigint, text, public.platform_preset, jsonb, public.project_version_reason) to service_role;

alter table public.projects enable row level security;
alter table public.project_versions enable row level security;

revoke all on table public.projects, public.project_versions from anon, authenticated, service_role;
grant select on table public.projects, public.project_versions to authenticated;
grant select, insert, update, delete on table public.projects, public.project_versions to service_role;

drop policy if exists projects_select_own_active on public.projects;
create policy projects_select_own_active
on public.projects
for select
to authenticated
using (
  (select auth.uid()) = owner_id
  and state in ('draft', 'archived')
  and exists (
    select 1 from public.profiles
    where profiles.id = (select auth.uid()) and profiles.status = 'active'
  )
);

drop policy if exists project_versions_select_own_active on public.project_versions;
create policy project_versions_select_own_active
on public.project_versions
for select
to authenticated
using (
  (select auth.uid()) = owner_id
  and exists (
    select 1 from public.projects
    where projects.id = project_id
      and projects.owner_id = (select auth.uid())
      and projects.state in ('draft', 'archived')
  )
  and exists (
    select 1 from public.profiles
    where profiles.id = (select auth.uid()) and profiles.status = 'active'
  )
);

-- source: supabase/definitions/assets.sql
do $$
begin
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'brand_kit_state') then
    create type public.brand_kit_state as enum ('active', 'deleting', 'deleted');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'asset_kind') then
    create type public.asset_kind as enum ('upload', 'stock', 'screenshot', 'ai_image', 'portrait', 'audio', 'derived');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'asset_purpose') then
    create type public.asset_purpose as enum ('source', 'media', 'export', 'tool_output', 'account_export');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'asset_state') then
    create type public.asset_state as enum ('pending_upload', 'validating', 'ready', 'failed', 'deleting', 'deleted');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'source_kind') then
    create type public.source_kind as enum ('topic', 'text', 'url', 'pdf', 'slides', 'video');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'source_state') then
    create type public.source_state as enum ('uploading', 'parsing', 'ready', 'failed', 'deleted');
  end if;
end
$$;

comment on type public.brand_kit_state is '品牌配置生命周期状态';
comment on type public.asset_kind is '素材来源或派生类别';
comment on type public.asset_purpose is '对象用途与授权策略类别';
comment on type public.asset_state is '素材验证与删除状态';
comment on type public.source_kind is '注册用户来源输入类别';
comment on type public.source_state is '来源上传、解析和清理状态';

insert into storage.buckets (id, name, public)
values ('sources', 'sources', false), ('assets', 'assets', false)
on conflict (id) do update set public = false;

create table if not exists public.brand_kits (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users (id) on delete restrict,
  name text not null check (length(btrim(name)) between 1 and 100),
  settings jsonb not null default '{}'::jsonb check (jsonb_typeof(settings) = 'object'),
  revision bigint not null default 1 check (revision >= 1),
  state public.brand_kit_state not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.brand_kits is '可复用品牌配置';
comment on column public.brand_kits.id is '品牌唯一标识';
comment on column public.brand_kits.owner_id is '品牌所有者标识';
comment on column public.brand_kits.name is '品牌名称';
comment on column public.brand_kits.settings is '显示名称、网站、CTA、颜色、字体、页码配置及资源引用';
comment on column public.brand_kits.revision is '品牌配置乐观并发版本';
comment on column public.brand_kits.state is '品牌生命周期状态';
comment on column public.brand_kits.created_at is '创建时间（UTC）';
comment on column public.brand_kits.updated_at is '最近修改时间（UTC）';

create table if not exists public.assets (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users (id) on delete restrict,
  kind public.asset_kind not null,
  purpose public.asset_purpose not null,
  bucket text not null check (bucket in ('sources', 'assets', 'exports')),
  object_key text not null check (length(object_key) > 0 and object_key !~ '(^/|(^|/)\.\.(/|$))'),
  mime text not null check (length(btrim(mime)) > 0),
  bytes bigint not null check (bytes >= 0),
  sha256 text not null check (sha256 ~ '^[0-9a-f]{64}$'),
  width integer check (width is null or width > 0),
  height integer check (height is null or height > 0),
  duration_ms bigint check (duration_ms is null or duration_ms >= 0),
  parent_asset_id uuid references public.assets (id) on delete restrict,
  rights jsonb not null default '{}'::jsonb check (jsonb_typeof(rights) = 'object'),
  accepted_at timestamptz,
  library_retained boolean not null default false,
  state public.asset_state not null default 'pending_upload',
  error_code text,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (bucket, object_key),
  constraint assets_ready_metadata_check check (
    state <> 'ready' or (bytes > 0 and sha256 <> repeat('0', 64))
  )
);

comment on table public.assets is '用户素材、来源文件及处理后派生文件元数据';
comment on column public.assets.id is '素材唯一标识';
comment on column public.assets.owner_id is '素材所有者标识';
comment on column public.assets.kind is '上传、图库、截图、AI、音频或派生类别';
comment on column public.assets.purpose is '来源、媒体、导出、工具产物或账号导出用途';
comment on column public.assets.bucket is '私有 Storage 桶标识';
comment on column public.assets.object_key is '不可猜测且不可覆盖的对象键';
comment on column public.assets.mime is '服务端检测的媒体类型';
comment on column public.assets.bytes is '服务端检测的实际字节数';
comment on column public.assets.sha256 is '对象内容 SHA-256 校验值';
comment on column public.assets.width is '图片像素宽度';
comment on column public.assets.height is '图片像素高度';
comment on column public.assets.duration_ms is '媒体时长（毫秒）';
comment on column public.assets.parent_asset_id is '派生素材的源素材标识';
comment on column public.assets.rights is '来源、作者、许可、用户确认及供应商版本';
comment on column public.assets.accepted_at is '用户接受 AI 候选素材的时间（UTC）';
comment on column public.assets.library_retained is '用户是否明确将素材保留在个人素材库';
comment on column public.assets.state is '素材上传、验证、可用、失败或删除状态';
comment on column public.assets.error_code is '可向用户公开的安全错误类别';
comment on column public.assets.deleted_at is '物理对象删除完成时间（UTC）';
comment on column public.assets.created_at is '创建时间（UTC）';
comment on column public.assets.updated_at is '最近修改时间（UTC）';

create table if not exists public.sources (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users (id) on delete restrict,
  project_id uuid references public.projects (id) on delete restrict,
  kind public.source_kind not null,
  asset_id uuid references public.assets (id) on delete restrict,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  segments jsonb not null default '[]'::jsonb check (jsonb_typeof(segments) in ('array', 'object')),
  state public.source_state not null default 'uploading',
  expires_at timestamptz not null default (now() + interval '7 days'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sources_file_kind_check check (
    (kind in ('pdf', 'slides', 'video') and asset_id is not null)
    or (kind in ('topic', 'text', 'url'))
  )
);

comment on table public.sources is '已注册用户的输入资产及解析定位';
comment on column public.sources.id is '来源唯一标识';
comment on column public.sources.owner_id is '来源所有者标识';
comment on column public.sources.project_id is '可选所属项目标识';
comment on column public.sources.kind is 'Topic、Text、URL、PDF、Slides 或 Video 输入类别';
comment on column public.sources.asset_id is '来源原始文件的素材标识';
comment on column public.sources.metadata is '来源标题、公开 URL、页数或时长等安全元数据';
comment on column public.sources.segments is '带稳定 segmentId 和页码或时间定位的解析段落';
comment on column public.sources.state is '来源上传、解析、可用、失败或删除状态';
comment on column public.sources.expires_at is '原始正文及文件清理时间（UTC）';
comment on column public.sources.created_at is '创建时间（UTC）';
comment on column public.sources.updated_at is '最近修改时间（UTC）';

create table if not exists public.project_asset_refs (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete restrict,
  version_id uuid references public.project_versions (id) on delete restrict,
  asset_id uuid not null references public.assets (id) on delete restrict,
  slot_key text not null check (length(btrim(slot_key)) > 0),
  created_at timestamptz not null default now()
);

comment on table public.project_asset_refs is '当前项目及历史版本的素材引用保护';
comment on column public.project_asset_refs.id is '引用唯一标识';
comment on column public.project_asset_refs.project_id is '所属项目标识';
comment on column public.project_asset_refs.version_id is '历史快照标识，为空表示当前稿';
comment on column public.project_asset_refs.asset_id is '被引用的素材标识';
comment on column public.project_asset_refs.slot_key is '文档内引用槽位';
comment on column public.project_asset_refs.created_at is '建立时间（UTC）';

create unique index if not exists project_asset_refs_current_unique
on public.project_asset_refs (project_id, asset_id, slot_key) where version_id is null;
create unique index if not exists project_asset_refs_version_unique
on public.project_asset_refs (version_id, asset_id, slot_key) where version_id is not null;

create table if not exists public.brand_asset_refs (
  brand_kit_id uuid not null references public.brand_kits (id) on delete restrict,
  asset_id uuid not null references public.assets (id) on delete restrict,
  slot_key text not null check (length(btrim(slot_key)) > 0),
  created_at timestamptz not null default now(),
  primary key (brand_kit_id, asset_id, slot_key)
);

comment on table public.brand_asset_refs is '品牌配置的素材引用保护';
comment on column public.brand_asset_refs.brand_kit_id is '品牌配置标识';
comment on column public.brand_asset_refs.asset_id is '被引用的素材标识';
comment on column public.brand_asset_refs.slot_key is 'logo、headshot 等品牌用途';
comment on column public.brand_asset_refs.created_at is '建立时间（UTC）';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.projects'::regclass and conname = 'projects_brand_kit_id_fkey'
  ) then
    alter table public.projects
    add constraint projects_brand_kit_id_fkey
    foreign key (brand_kit_id) references public.brand_kits (id) on delete restrict;
  end if;
end
$$;

create index if not exists brand_kits_owner_state_idx on public.brand_kits (owner_id, state);
create index if not exists assets_owner_state_idx on public.assets (owner_id, state);
create index if not exists assets_parent_asset_id_idx on public.assets (parent_asset_id) where parent_asset_id is not null;
create index if not exists sources_owner_state_idx on public.sources (owner_id, state);
create index if not exists sources_expires_at_idx on public.sources (expires_at) where state <> 'deleted';
create index if not exists sources_project_id_idx on public.sources (project_id) where project_id is not null;
create index if not exists sources_asset_id_idx on public.sources (asset_id) where asset_id is not null;
create index if not exists project_asset_refs_project_id_idx on public.project_asset_refs (project_id);
create index if not exists project_asset_refs_asset_id_idx on public.project_asset_refs (asset_id);
create index if not exists brand_asset_refs_asset_id_idx on public.brand_asset_refs (asset_id);
create index if not exists projects_brand_kit_id_idx on public.projects (brand_kit_id) where brand_kit_id is not null;

create or replace function private.sync_project_brand_kit_id()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  requested_brand_id text;
begin
  requested_brand_id := nullif(new.document #>> '{brandSnapshot,kitId}', '');
  new.brand_kit_id := null;
  if requested_brand_id ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then
    select id into new.brand_kit_id from public.brand_kits
    where id = requested_brand_id::uuid and owner_id = new.owner_id and state = 'active';
  end if;
  return new;
end;
$$;

comment on function private.sync_project_brand_kit_id() is '从 CarouselDocument 品牌快照同步项目品牌引用，供影响检查和引用约束使用';

drop trigger if exists projects_sync_brand_kit_id on public.projects;
create trigger projects_sync_brand_kit_id
before insert or update of document on public.projects
for each row execute function private.sync_project_brand_kit_id();

comment on trigger projects_sync_brand_kit_id on public.projects is '项目文档写入时同步 brand_kit_id';

create or replace function private.enforce_owned_resource_links()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  referenced_owner uuid;
  second_owner uuid;
begin
  if tg_table_name = 'assets' then
    if new.parent_asset_id is not null then
      select owner_id into referenced_owner from public.assets where id = new.parent_asset_id;
      if referenced_owner is distinct from new.owner_id then
        raise exception using errcode = '23514', message = 'asset parent must have the same owner';
      end if;
    end if;
  elsif tg_table_name = 'sources' then
    if new.project_id is not null then
      select owner_id into referenced_owner from public.projects where id = new.project_id;
      if referenced_owner is distinct from new.owner_id then
        raise exception using errcode = '23514', message = 'source project must have the same owner';
      end if;
    end if;
    if new.asset_id is not null then
      select owner_id into referenced_owner from public.assets where id = new.asset_id;
      if referenced_owner is distinct from new.owner_id then
        raise exception using errcode = '23514', message = 'source asset must have the same owner';
      end if;
    end if;
  elsif tg_table_name = 'project_asset_refs' then
    select owner_id into referenced_owner from public.projects where id = new.project_id;
    select owner_id into second_owner from public.assets where id = new.asset_id;
    if referenced_owner is distinct from second_owner then
      raise exception using errcode = '23514', message = 'project and asset must have the same owner';
    end if;
    if new.version_id is not null and not exists (
      select 1 from public.project_versions
      where id = new.version_id and project_id = new.project_id and owner_id = referenced_owner
    ) then
      raise exception using errcode = '23514', message = 'version must belong to the referenced project';
    end if;
  elsif tg_table_name = 'brand_asset_refs' then
    select owner_id into referenced_owner from public.brand_kits where id = new.brand_kit_id;
    select owner_id into second_owner from public.assets where id = new.asset_id;
    if referenced_owner is distinct from second_owner then
      raise exception using errcode = '23514', message = 'brand and asset must have the same owner';
    end if;
  elsif tg_table_name = 'projects' and new.brand_kit_id is not null then
    select owner_id into referenced_owner from public.brand_kits where id = new.brand_kit_id;
    if referenced_owner is distinct from new.owner_id then
      raise exception using errcode = '23514', message = 'project and brand must have the same owner';
    end if;
  end if;
  return new;
end;
$$;

comment on function private.enforce_owned_resource_links() is '拒绝项目、品牌、来源和素材之间的跨账户引用';
revoke execute on function private.enforce_owned_resource_links() from public, anon, authenticated, service_role;

drop trigger if exists assets_enforce_owned_parent on public.assets;
create trigger assets_enforce_owned_parent before insert or update of owner_id, parent_asset_id on public.assets
for each row execute function private.enforce_owned_resource_links();
drop trigger if exists sources_enforce_owned_links on public.sources;
create trigger sources_enforce_owned_links before insert or update of owner_id, project_id, asset_id on public.sources
for each row execute function private.enforce_owned_resource_links();
drop trigger if exists project_asset_refs_enforce_owner on public.project_asset_refs;
create trigger project_asset_refs_enforce_owner before insert or update on public.project_asset_refs
for each row execute function private.enforce_owned_resource_links();
drop trigger if exists brand_asset_refs_enforce_owner on public.brand_asset_refs;
create trigger brand_asset_refs_enforce_owner before insert or update on public.brand_asset_refs
for each row execute function private.enforce_owned_resource_links();
drop trigger if exists projects_enforce_brand_owner on public.projects;
create trigger projects_enforce_brand_owner before insert or update of owner_id, brand_kit_id on public.projects
for each row execute function private.enforce_owned_resource_links();

alter table public.brand_kits enable row level security;
alter table public.assets enable row level security;
alter table public.sources enable row level security;
alter table public.project_asset_refs enable row level security;
alter table public.brand_asset_refs enable row level security;

revoke all on table public.brand_kits, public.assets, public.sources, public.project_asset_refs, public.brand_asset_refs from anon, authenticated, service_role;
grant select on table public.brand_kits, public.assets, public.sources, public.project_asset_refs, public.brand_asset_refs to authenticated;
grant select, insert, update, delete on table public.brand_kits, public.assets, public.sources, public.project_asset_refs, public.brand_asset_refs to service_role;

drop policy if exists brand_kits_select_own_active on public.brand_kits;
create policy brand_kits_select_own_active on public.brand_kits for select to authenticated
using ((select auth.uid()) = owner_id and state = 'active' and exists (select 1 from public.profiles where id = (select auth.uid()) and status = 'active'));
drop policy if exists assets_select_own_available on public.assets;
create policy assets_select_own_available on public.assets for select to authenticated
using ((select auth.uid()) = owner_id and state not in ('deleting', 'deleted') and exists (select 1 from public.profiles where id = (select auth.uid()) and status = 'active'));
drop policy if exists sources_select_own_unexpired on public.sources;
create policy sources_select_own_unexpired on public.sources for select to authenticated
using ((select auth.uid()) = owner_id and state <> 'deleted' and expires_at > now() and exists (select 1 from public.profiles where id = (select auth.uid()) and status = 'active'));
drop policy if exists project_asset_refs_select_own_active on public.project_asset_refs;
create policy project_asset_refs_select_own_active on public.project_asset_refs for select to authenticated
using (exists (select 1 from public.projects where id = project_id and owner_id = (select auth.uid()) and state in ('draft', 'archived')));
drop policy if exists brand_asset_refs_select_own_active on public.brand_asset_refs;
create policy brand_asset_refs_select_own_active on public.brand_asset_refs for select to authenticated
using (exists (select 1 from public.brand_kits where id = brand_kit_id and owner_id = (select auth.uid()) and state = 'active'));

drop policy if exists storage_download_owned_or_referenced_assets on storage.objects;
create policy storage_download_owned_or_referenced_assets
on storage.objects for select to authenticated
using (
  bucket_id in ('sources', 'assets')
  and exists (
    select 1
    from public.assets
    where assets.bucket = storage.objects.bucket_id
      and assets.object_key = storage.objects.name
      and assets.owner_id = (select auth.uid())
      and assets.state not in ('deleting', 'deleted')
      and exists (select 1 from public.profiles where id = (select auth.uid()) and status = 'active')
      and (
        (assets.purpose = 'source' and (
          exists (select 1 from public.sources where asset_id = assets.id and state <> 'deleted' and expires_at > now())
          or (assets.created_at > now() - interval '24 hours' and assets.state in ('pending_upload', 'validating', 'ready'))
        ))
        or (assets.purpose = 'media' and assets.state = 'ready'
          and (assets.kind not in ('ai_image', 'portrait') or assets.accepted_at is not null)
          and (
          assets.library_retained
          or exists (select 1 from public.project_asset_refs where asset_id = assets.id)
          or exists (select 1 from public.brand_asset_refs where asset_id = assets.id)
        ))
      )
  )
);

-- source: supabase/definitions/jobs-usage.sql
do $$
begin
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'job_kind') then
    create type public.job_kind as enum ('generation', 'rewrite', 'parse', 'asset', 'export', 'tool', 'cleanup', 'account_export', 'import');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'job_state') then
    create type public.job_state as enum ('pending_dispatch', 'queued', 'running', 'succeeded', 'partial', 'failed', 'canceled');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'usage_ledger_kind') then
    create type public.usage_ledger_kind as enum ('grant', 'reserve', 'settle', 'release', 'reversal');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'private'::regnamespace and typname = 'cost_reservation_state') then
    create type private.cost_reservation_state as enum ('open', 'unknown', 'settled', 'released');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'private'::regnamespace and typname = 'cost_attempt_state') then
    create type private.cost_attempt_state as enum ('planned', 'sent', 'unknown', 'settled');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'private'::regnamespace and typname = 'operation_receipt_status') then
    create type private.operation_receipt_status as enum ('completed', 'failed');
  end if;
end
$$;

comment on type public.job_kind is '后台任务业务类别';
comment on type public.job_state is '后台任务 outbox 与执行状态';
comment on type public.usage_ledger_kind is '用户额度流水类别';
comment on type private.cost_reservation_state is '供应商成本预留状态';
comment on type private.cost_attempt_state is '供应商单次调用状态';
comment on type private.operation_receipt_status is '非任务写操作回执结果类别';

create table if not exists public.jobs (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users (id) on delete restrict,
  project_id uuid references public.projects (id) on delete restrict,
  parent_job_id uuid references public.jobs (id) on delete restrict,
  kind public.job_kind not null,
  input_ref jsonb not null check (jsonb_typeof(input_ref) = 'object'),
  idempotency_key text not null check (length(btrim(idempotency_key)) between 1 and 200),
  request_hash text not null check (length(request_hash) >= 32),
  state public.job_state not null default 'pending_dispatch',
  stage text not null default 'validate' check (stage in ('validate', 'parse', 'transcribe', 'outline', 'write', 'layout', 'render', 'package', 'upload')),
  progress integer not null default 0 check (progress between 0 and 100),
  provider_run_id text,
  attempt integer not null default 0 check (attempt between 0 and 3),
  lease_token uuid,
  heartbeat_at timestamptz,
  result_ref jsonb check (result_ref is null or jsonb_typeof(result_ref) = 'object'),
  error_code text,
  cancel_requested_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  finished_at timestamptz,
  unique (owner_id, kind, idempotency_key),
  constraint jobs_terminal_timestamp_check check ((state in ('succeeded', 'partial', 'failed', 'canceled')) = (finished_at is not null)),
  constraint jobs_terminal_progress_check check (state not in ('succeeded', 'partial') or progress = 100)
);

comment on table public.jobs is '异步任务、状态机与事务 outbox';
comment on column public.jobs.id is '业务任务唯一标识';
comment on column public.jobs.owner_id is '任务所有者标识';
comment on column public.jobs.project_id is '可选所属项目标识';
comment on column public.jobs.parent_job_id is '多格式协调父任务标识';
comment on column public.jobs.kind is '生成、改写、解析、素材、导出、工具或清理任务类别';
comment on column public.jobs.input_ref is '仅含已授权对象 ID、参数及基础版本的任务输入引用';
comment on column public.jobs.idempotency_key is '同类逻辑请求的客户端幂等键';
comment on column public.jobs.request_hash is '任务参数一致性摘要，不含原文';
comment on column public.jobs.state is '事务 outbox 与后台执行状态';
comment on column public.jobs.stage is '当前实际执行阶段';
comment on column public.jobs.progress is '已完成单位折算的阶段进度';
comment on column public.jobs.provider_run_id is '云任务供应商运行标识';
comment on column public.jobs.attempt is '当前后台尝试序号';
comment on column public.jobs.lease_token is '当前尝试写回令牌';
comment on column public.jobs.heartbeat_at is '后台任务最近活动时间（UTC）';
comment on column public.jobs.result_ref is '候选内容或结果资源的安全引用';
comment on column public.jobs.error_code is '可向用户公开的错误类别';
comment on column public.jobs.cancel_requested_at is '取消请求持久化时间（UTC）';
comment on column public.jobs.created_at is '创建时间（UTC）';
comment on column public.jobs.updated_at is '最近修改时间（UTC）';
comment on column public.jobs.finished_at is '终态提交时间（UTC）';

create table if not exists public.usage_accounts (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users (id) on delete restrict,
  period_start timestamptz not null,
  period_end timestamptz not null,
  resource text not null check (length(btrim(resource)) > 0),
  granted bigint not null default 0 check (granted >= 0),
  reserved bigint not null default 0 check (reserved >= 0),
  consumed bigint not null default 0 check (consumed >= 0),
  updated_at timestamptz not null default now(),
  unique (owner_id, period_start, resource),
  constraint usage_accounts_period_check check (period_end > period_start),
  constraint usage_accounts_balance_check check (reserved + consumed <= granted)
);

comment on table public.usage_accounts is '用户权益周期内的额度桶';
comment on column public.usage_accounts.id is '额度桶唯一标识';
comment on column public.usage_accounts.owner_id is '额度所有者标识';
comment on column public.usage_accounts.period_start is '权益周期开始时间（UTC）';
comment on column public.usage_accounts.period_end is '权益周期结束时间（UTC）';
comment on column public.usage_accounts.resource is 'generation、image、minute 或 export 等资源类别';
comment on column public.usage_accounts.granted is '周期授予额度单位';
comment on column public.usage_accounts.reserved is '尚未结算的预留额度单位';
comment on column public.usage_accounts.consumed is '已经结算的消耗额度单位';
comment on column public.usage_accounts.updated_at is '最近修改时间（UTC）';

create table if not exists public.usage_ledger (
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null references public.usage_accounts (id) on delete restrict,
  job_id uuid references public.jobs (id) on delete restrict,
  event_key text not null unique check (length(btrim(event_key)) > 0),
  kind public.usage_ledger_kind not null,
  units bigint not null check (units > 0),
  created_at timestamptz not null default now()
);

comment on table public.usage_ledger is '只追加的用户额度流水';
comment on column public.usage_ledger.id is '流水唯一标识';
comment on column public.usage_ledger.account_id is '关联额度桶标识';
comment on column public.usage_ledger.job_id is '可选关联任务标识';
comment on column public.usage_ledger.event_key is '幂等业务事件唯一键';
comment on column public.usage_ledger.kind is '授予、预留、结算、释放或反冲类别';
comment on column public.usage_ledger.units is '本次流水涉及的正数额度单位';
comment on column public.usage_ledger.created_at is '流水发生时间（UTC）';

create table if not exists private.cost_budgets (
  period text not null check (period ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  environment text not null check (environment in ('development', 'preview', 'production')),
  limit_micro_usd bigint not null check (limit_micro_usd >= 0),
  reserved_micro_usd bigint not null default 0 check (reserved_micro_usd >= 0),
  spent_micro_usd bigint not null default 0 check (spent_micro_usd >= 0),
  updated_at timestamptz not null default now(),
  primary key (period, environment)
);

comment on table private.cost_budgets is '环境 UTC 月度 AI 供应商成本预算';
comment on column private.cost_budgets.period is 'UTC 月份，格式 YYYY-MM';
comment on column private.cost_budgets.environment is '预算归属部署环境';
comment on column private.cost_budgets.limit_micro_usd is '预算上限，单位微美元';
comment on column private.cost_budgets.reserved_micro_usd is '未结算预留，单位微美元';
comment on column private.cost_budgets.spent_micro_usd is '已确认实际成本，单位微美元';
comment on column private.cost_budgets.updated_at is '最近修改时间（UTC）';

create table if not exists private.request_guards (
  id uuid primary key default gen_random_uuid(),
  subject_hash text not null check (length(subject_hash) >= 32),
  operation_key text not null check (length(btrim(operation_key)) > 0),
  request_hash text not null check (length(request_hash) >= 32),
  state text not null,
  window_start timestamptz not null,
  count integer not null default 1 check (count > 0),
  expires_at timestamptz not null,
  unique (subject_hash, operation_key),
  constraint request_guards_expiry_check check (expires_at > window_start)
);

comment on table private.request_guards is '匿名与注册请求的去重和速率窗口安全元数据';
comment on column private.request_guards.id is '保护记录唯一标识';
comment on column private.request_guards.subject_hash is '带环境盐的主体窗口摘要，不存原始 IP';
comment on column private.request_guards.operation_key is '请求操作唯一编号';
comment on column private.request_guards.request_hash is '不含正文的 HMAC 输入摘要';
comment on column private.request_guards.state is '请求处理状态';
comment on column private.request_guards.window_start is '速率计数窗口开始时间（UTC）';
comment on column private.request_guards.count is '窗口内请求次数';
comment on column private.request_guards.expires_at is '保护元数据清理时间（UTC）';

create table if not exists private.cost_reservations (
  id uuid primary key default gen_random_uuid(),
  job_id uuid references public.jobs (id) on delete restrict,
  guest_guard_id uuid,
  environment text not null check (environment in ('development', 'preview', 'production')),
  period text not null check (period ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  operation_key text not null unique,
  reserved_micro_usd bigint not null check (reserved_micro_usd >= 0),
  settled_micro_usd bigint not null default 0 check (settled_micro_usd >= 0),
  released_micro_usd bigint not null default 0 check (released_micro_usd >= 0),
  state private.cost_reservation_state not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cost_reservations_subject_check check ((job_id is not null)::integer + (guest_guard_id is not null)::integer = 1),
  constraint cost_reservations_release_check check (released_micro_usd <= reserved_micro_usd)
);

comment on table private.cost_reservations is '请求级可恢复供应商成本预留';
comment on column private.cost_reservations.id is '成本预留唯一标识';
comment on column private.cost_reservations.job_id is '可选注册任务标识';
comment on column private.cost_reservations.guest_guard_id is '可选匿名保护记录标识，不建立延长保留的外键';
comment on column private.cost_reservations.environment is '预算归属部署环境';
comment on column private.cost_reservations.period is '预算归属 UTC 月份';
comment on column private.cost_reservations.operation_key is '逻辑成本预留幂等键';
comment on column private.cost_reservations.reserved_micro_usd is '预留金额，单位微美元';
comment on column private.cost_reservations.settled_micro_usd is '已结算金额，单位微美元';
comment on column private.cost_reservations.released_micro_usd is '已释放金额，单位微美元';
comment on column private.cost_reservations.state is '开放、未知、已结算或已释放状态';
comment on column private.cost_reservations.created_at is '创建时间（UTC）';
comment on column private.cost_reservations.updated_at is '最近修改时间（UTC）';

create table if not exists private.cost_attempts (
  id uuid primary key default gen_random_uuid(),
  reservation_id uuid not null references private.cost_reservations (id) on delete restrict,
  attempt_key text not null unique,
  provider_operation_id text,
  state private.cost_attempt_state not null default 'planned',
  usage jsonb not null default '{}'::jsonb check (jsonb_typeof(usage) = 'object'),
  actual_micro_usd bigint check (actual_micro_usd is null or actual_micro_usd >= 0),
  started_at timestamptz not null default now(),
  settled_at timestamptz,
  constraint cost_attempts_settlement_check check ((state = 'settled') = (settled_at is not null and actual_micro_usd is not null))
);

comment on table private.cost_attempts is '每次供应商调用的最小化成本审计';
comment on column private.cost_attempts.id is '供应商调用尝试唯一标识';
comment on column private.cost_attempts.reservation_id is '关联请求级成本预留标识';
comment on column private.cost_attempts.attempt_key is '任务、阶段和尝试序号组成的幂等键';
comment on column private.cost_attempts.provider_operation_id is '可选供应商对账编号';
comment on column private.cost_attempts.state is '计划、已发送、未知或已结算状态';
comment on column private.cost_attempts.usage is '仅含 token、分钟或秒数等数字用量';
comment on column private.cost_attempts.actual_micro_usd is '确认的实际成本，单位微美元';
comment on column private.cost_attempts.started_at is '供应商调用开始时间（UTC）';
comment on column private.cost_attempts.settled_at is '成本结算时间（UTC）';

create table if not exists private.operation_receipts (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users (id) on delete restrict,
  operation text not null,
  idempotency_key text not null,
  request_hash text not null check (length(request_hash) >= 32),
  status private.operation_receipt_status not null,
  response_ref jsonb not null check (jsonb_typeof(response_ref) = 'object'),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 days'),
  unique (owner_id, operation, idempotency_key),
  constraint operation_receipts_expiry_check check (expires_at > created_at)
);

comment on table private.operation_receipts is '非任务写操作的幂等回执';
comment on column private.operation_receipts.id is '回执唯一标识';
comment on column private.operation_receipts.owner_id is '操作所有者标识';
comment on column private.operation_receipts.operation is '端点及资源类型';
comment on column private.operation_receipts.idempotency_key is '客户端操作幂等键';
comment on column private.operation_receipts.request_hash is '不含正文的请求 HMAC 摘要';
comment on column private.operation_receipts.status is '完成或失败的结果类别';
comment on column private.operation_receipts.response_ref is '仅含对象标识、revision、状态及 HTTP 码的安全响应引用';
comment on column private.operation_receipts.created_at is '创建时间（UTC）';
comment on column private.operation_receipts.expires_at is '完整回执保留截止时间（UTC）';

create index if not exists jobs_state_updated_idx on public.jobs (state, updated_at);
create index if not exists jobs_owner_created_idx on public.jobs (owner_id, created_at desc);
create index if not exists jobs_project_id_idx on public.jobs (project_id) where project_id is not null;
create index if not exists jobs_parent_job_id_idx on public.jobs (parent_job_id) where parent_job_id is not null;
create index if not exists usage_accounts_owner_period_idx on public.usage_accounts (owner_id, period_end);
create index if not exists usage_ledger_account_id_idx on public.usage_ledger (account_id);
create index if not exists usage_ledger_job_id_idx on public.usage_ledger (job_id) where job_id is not null;
create index if not exists cost_reservations_job_id_idx on private.cost_reservations (job_id) where job_id is not null;
create index if not exists cost_attempts_reservation_id_idx on private.cost_attempts (reservation_id);
create index if not exists operation_receipts_expiry_idx on private.operation_receipts (expires_at);
create index if not exists request_guards_expiry_idx on private.request_guards (expires_at);

create or replace function private.reject_usage_ledger_mutation()
returns trigger language plpgsql set search_path = '' as $$
begin
  raise exception using errcode = '55000', message = 'usage ledger is append-only';
end;
$$;
comment on function private.reject_usage_ledger_mutation() is '阻止额度流水被更新或删除';
revoke execute on function private.reject_usage_ledger_mutation() from public, anon, authenticated, service_role;
drop trigger if exists usage_ledger_is_append_only on public.usage_ledger;
create trigger usage_ledger_is_append_only before update or delete on public.usage_ledger
for each row execute function private.reject_usage_ledger_mutation();

create or replace function private.submit_job(
  p_owner_id uuid, p_project_id uuid, p_kind public.job_kind, p_input_ref jsonb,
  p_idempotency_key text, p_request_hash text, p_resource text, p_units bigint,
  p_period_start timestamptz, p_period_end timestamptz,
  p_environment text, p_cost_period text, p_reserved_micro_usd bigint
)
returns public.jobs language plpgsql security definer set search_path = '' as $$
declare
  existing_job public.jobs;
  created_job public.jobs;
  usage_account public.usage_accounts;
  cost_budget private.cost_budgets;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_owner_id::text || ':job:' || p_kind::text || ':' || p_idempotency_key, 0));
  select * into existing_job from public.jobs
  where owner_id = p_owner_id and kind = p_kind and idempotency_key = p_idempotency_key;
  if existing_job.id is not null then
    if existing_job.request_hash <> p_request_hash then
      raise exception using errcode = '23505', message = 'idempotency key request hash conflict';
    end if;
    return existing_job;
  end if;

  if not exists (select 1 from public.profiles where id = p_owner_id and status = 'active') then
    raise exception using errcode = '42501', message = 'account is not active';
  end if;
  if p_project_id is not null and not exists (
    select 1 from public.projects where id = p_project_id and owner_id = p_owner_id and state in ('draft', 'archived')
  ) then
    raise exception using errcode = '42501', message = 'project is not accessible';
  end if;

  select * into usage_account from public.usage_accounts
  where owner_id = p_owner_id and period_start = p_period_start and resource = p_resource
    and period_end = p_period_end and now() >= period_start and now() < period_end
  for update;
  if usage_account.id is null or p_units <= 0 or usage_account.granted - usage_account.reserved - usage_account.consumed < p_units then
    raise exception using errcode = '22003', message = 'insufficient usage balance';
  end if;

  select * into cost_budget from private.cost_budgets
  where period = p_cost_period and environment = p_environment for update;
  if cost_budget.period is null or p_reserved_micro_usd < 0
    or cost_budget.limit_micro_usd - cost_budget.reserved_micro_usd - cost_budget.spent_micro_usd < p_reserved_micro_usd then
    raise exception using errcode = '22003', message = 'environment cost budget exceeded';
  end if;

  insert into public.jobs (owner_id, project_id, kind, input_ref, idempotency_key, request_hash)
  values (p_owner_id, p_project_id, p_kind, p_input_ref, p_idempotency_key, p_request_hash)
  returning * into created_job;
  update public.usage_accounts set reserved = reserved + p_units, updated_at = now() where id = usage_account.id;
  insert into public.usage_ledger (account_id, job_id, event_key, kind, units)
  values (usage_account.id, created_job.id, 'job:' || created_job.id::text || ':reserve', 'reserve', p_units);
  update private.cost_budgets set reserved_micro_usd = reserved_micro_usd + p_reserved_micro_usd, updated_at = now()
  where period = p_cost_period and environment = p_environment;
  insert into private.cost_reservations (job_id, environment, period, operation_key, reserved_micro_usd)
  values (created_job.id, p_environment, p_cost_period, 'job:' || created_job.id::text, p_reserved_micro_usd);
  return created_job;
end;
$$;
comment on function private.submit_job(uuid, uuid, public.job_kind, jsonb, text, text, text, bigint, timestamptz, timestamptz, text, text, bigint) is '幂等创建 outbox 任务并原子预留用户额度及环境成本';
revoke execute on function private.submit_job(uuid, uuid, public.job_kind, jsonb, text, text, text, bigint, timestamptz, timestamptz, text, text, bigint) from public, anon, authenticated;
grant execute on function private.submit_job(uuid, uuid, public.job_kind, jsonb, text, text, text, bigint, timestamptz, timestamptz, text, text, bigint) to service_role;

create or replace function private.register_cost_attempt(p_job_id uuid, p_attempt_key text)
returns uuid language plpgsql security definer set search_path = '' as $$
declare reservation uuid; attempt_id uuid;
begin
  select id into reservation from private.cost_reservations where job_id = p_job_id and state in ('open', 'unknown');
  if reservation is null then raise exception using errcode = '22023', message = 'open cost reservation not found'; end if;
  insert into private.cost_attempts (reservation_id, attempt_key)
  values (reservation, p_attempt_key)
  on conflict (attempt_key) do nothing
  returning id into attempt_id;
  if attempt_id is null then select id into attempt_id from private.cost_attempts where attempt_key = p_attempt_key; end if;
  return attempt_id;
end;
$$;
comment on function private.register_cost_attempt(uuid, text) is '发送供应商调用前幂等记录尝试';
revoke execute on function private.register_cost_attempt(uuid, text) from public, anon, authenticated;
grant execute on function private.register_cost_attempt(uuid, text) to service_role;

create or replace function private.settle_cost_attempt(
  p_job_id uuid,
  p_attempt_key text,
  p_provider_operation_id text,
  p_usage jsonb,
  p_actual_micro_usd bigint
)
returns uuid language plpgsql security definer set search_path = '' as $$
declare settled_attempt private.cost_attempts;
begin
  if p_actual_micro_usd < 0 or jsonb_typeof(p_usage) <> 'object' then
    raise exception using errcode = '22023', message = 'invalid cost attempt settlement';
  end if;
  select attempt.* into settled_attempt
  from private.cost_attempts as attempt
  join private.cost_reservations as reservation on reservation.id = attempt.reservation_id
  where reservation.job_id = p_job_id and attempt.attempt_key = p_attempt_key
  for update of attempt;
  if settled_attempt.id is null then
    raise exception using errcode = '22023', message = 'cost attempt not found';
  end if;
  if settled_attempt.state = 'settled' then
    if settled_attempt.provider_operation_id is distinct from p_provider_operation_id
      or settled_attempt.usage is distinct from p_usage
      or settled_attempt.actual_micro_usd is distinct from p_actual_micro_usd then
      raise exception using errcode = '23505', message = 'cost attempt settlement conflict';
    end if;
    return settled_attempt.id;
  end if;
  update private.cost_attempts
  set provider_operation_id = p_provider_operation_id,
      usage = p_usage,
      actual_micro_usd = p_actual_micro_usd,
      state = 'settled',
      settled_at = now()
  where id = settled_attempt.id
  returning * into settled_attempt;
  return settled_attempt.id;
end;
$$;
comment on function private.settle_cost_attempt(uuid, text, text, jsonb, bigint) is '幂等结算一次供应商调用的实际用量与成本，允许实际成本高于预估';
revoke execute on function private.settle_cost_attempt(uuid, text, text, jsonb, bigint) from public, anon, authenticated;
grant execute on function private.settle_cost_attempt(uuid, text, text, jsonb, bigint) to service_role;

create or replace function private.request_job_cancellation(p_owner_id uuid, p_job_id uuid)
returns public.jobs language plpgsql security definer set search_path = '' as $$
declare target_job public.jobs;
begin
  select * into target_job from public.jobs where id = p_job_id and owner_id = p_owner_id for update;
  if target_job.id is null then raise exception using errcode = '42501', message = 'job is not accessible'; end if;
  if target_job.state not in ('succeeded', 'partial', 'failed', 'canceled') then
    update public.jobs set cancel_requested_at = coalesce(cancel_requested_at, now()), updated_at = now()
    where id = p_job_id returning * into target_job;
  end if;
  return target_job;
end;
$$;
comment on function private.request_job_cancellation(uuid, uuid) is '与终态事务竞争并持久化任务取消请求';
revoke execute on function private.request_job_cancellation(uuid, uuid) from public, anon, authenticated;
grant execute on function private.request_job_cancellation(uuid, uuid) to service_role;

create or replace function private.finalize_job(
  p_owner_id uuid, p_job_id uuid, p_lease_token uuid, p_requested_state public.job_state,
  p_result_ref jsonb, p_error_code text, p_delivered_units bigint, p_actual_micro_usd bigint, p_event_key text
)
returns public.jobs language plpgsql security definer set search_path = '' as $$
declare
  target_job public.jobs;
  final_state public.job_state;
  reserved_units bigint;
  usage_account_id uuid;
  reservation private.cost_reservations;
begin
  if p_requested_state not in ('succeeded', 'partial', 'failed', 'canceled') then
    raise exception using errcode = '22023', message = 'final state required';
  end if;
  select * into target_job from public.jobs where id = p_job_id and owner_id = p_owner_id for update;
  if target_job.id is null then raise exception using errcode = '42501', message = 'job is not accessible'; end if;
  if target_job.state in ('succeeded', 'partial', 'failed', 'canceled') then return target_job; end if;
  if target_job.lease_token is distinct from p_lease_token then raise exception using errcode = '40001', message = 'stale worker lease'; end if;
  final_state := case when target_job.cancel_requested_at is not null then 'canceled'::public.job_state else p_requested_state end;

  select account_id, units into usage_account_id, reserved_units from public.usage_ledger
  where job_id = p_job_id and kind = 'reserve' order by created_at limit 1;
  if usage_account_id is null then raise exception using errcode = '22023', message = 'usage reservation not found'; end if;
  if (final_state in ('succeeded', 'partial') and p_delivered_units <> reserved_units)
    or (final_state in ('failed', 'canceled') and p_delivered_units <> 0) then
    raise exception using errcode = '22023', message = 'delivered units do not match terminal state';
  end if;
  update public.usage_accounts
  set reserved = reserved - reserved_units,
      consumed = consumed + p_delivered_units,
      updated_at = now()
  where id = usage_account_id and reserved >= reserved_units;
  if not found then raise exception using errcode = '22003', message = 'usage reservation invariant failed'; end if;
  insert into public.usage_ledger (account_id, job_id, event_key, kind, units)
  values (usage_account_id, p_job_id, p_event_key,
    case when p_delivered_units > 0 then 'settle'::public.usage_ledger_kind else 'release'::public.usage_ledger_kind end,
    case when p_delivered_units > 0 then p_delivered_units else reserved_units end);

  select * into reservation from private.cost_reservations where job_id = p_job_id for update;
  if reservation.id is null or reservation.state not in ('open', 'unknown') or p_actual_micro_usd < 0 then
    raise exception using errcode = '22003', message = 'cost reservation invariant failed';
  end if;
  if exists (
    select 1 from private.cost_attempts
    where reservation_id = reservation.id and state in ('sent', 'unknown')
  ) or coalesce((
    select sum(actual_micro_usd) from private.cost_attempts
    where reservation_id = reservation.id and state = 'settled'
  ), 0) <> p_actual_micro_usd then
    raise exception using errcode = '22003', message = 'cost attempt audit is incomplete';
  end if;
  update private.cost_budgets
  set reserved_micro_usd = reserved_micro_usd - reservation.reserved_micro_usd,
      spent_micro_usd = spent_micro_usd + p_actual_micro_usd,
      updated_at = now()
  where period = reservation.period and environment = reservation.environment
    and reserved_micro_usd >= reservation.reserved_micro_usd;
  if not found then raise exception using errcode = '22003', message = 'cost budget invariant failed'; end if;
  update private.cost_reservations
  set settled_micro_usd = p_actual_micro_usd,
      released_micro_usd = greatest(reservation.reserved_micro_usd - p_actual_micro_usd, 0),
      state = case when p_actual_micro_usd > 0 then 'settled'::private.cost_reservation_state else 'released'::private.cost_reservation_state end,
      updated_at = now()
  where id = reservation.id;

  update public.jobs
  set state = final_state,
      progress = case when final_state in ('succeeded', 'partial') then 100 else progress end,
      result_ref = case when final_state in ('succeeded', 'partial') then p_result_ref else null end,
      error_code = case when final_state in ('failed', 'canceled') then p_error_code else null end,
      updated_at = now(), finished_at = now()
  where id = p_job_id returning * into target_job;
  return target_job;
end;
$$;
comment on function private.finalize_job(uuid, uuid, uuid, public.job_state, jsonb, text, bigint, bigint, text) is '按当前 lease 一次性提交任务终态并结算或释放额度和成本';
revoke execute on function private.finalize_job(uuid, uuid, uuid, public.job_state, jsonb, text, bigint, bigint, text) from public, anon, authenticated;
grant execute on function private.finalize_job(uuid, uuid, uuid, public.job_state, jsonb, text, bigint, bigint, text) to service_role;

drop function if exists private.save_project(uuid, uuid, bigint, text, public.platform_preset, jsonb, public.project_version_reason);
create or replace function private.save_project(
  p_owner_id uuid, p_project_id uuid, p_expected_revision bigint, p_title text,
  p_platform public.platform_preset, p_document jsonb, p_reason public.project_version_reason,
  p_idempotency_key text, p_request_hash text
)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare saved_project public.projects; receipt private.operation_receipts; response jsonb; operation_name text;
begin
  operation_name := 'save_project:' || p_project_id::text;
  perform pg_advisory_xact_lock(hashtextextended(p_owner_id::text || ':' || operation_name || ':' || p_idempotency_key, 0));
  select * into receipt from private.operation_receipts
  where owner_id = p_owner_id and operation = operation_name and idempotency_key = p_idempotency_key;
  if receipt.id is not null then
    if receipt.request_hash <> p_request_hash then raise exception using errcode = '23505', message = 'idempotency key request hash conflict'; end if;
    if receipt.expires_at <= now() then raise exception using errcode = '55000', message = 'operation receipt expired'; end if;
    if not exists (select 1 from public.projects where id = p_project_id and owner_id = p_owner_id and state in ('draft', 'archived')) then
      raise exception using errcode = '42501', message = 'project is not accessible';
    end if;
    return receipt.response_ref;
  end if;
  if not exists (select 1 from public.profiles where id = p_owner_id and status = 'active') then
    raise exception using errcode = '42501', message = 'account is not active';
  end if;
  update public.projects set title = p_title, platform = p_platform, document = p_document,
    revision = revision + 1, updated_at = now()
  where id = p_project_id and owner_id = p_owner_id and state in ('draft', 'archived')
    and revision = p_expected_revision
  returning * into saved_project;
  if saved_project.id is null then raise exception using errcode = '40001', message = 'project revision conflict'; end if;
  insert into public.project_versions (project_id, owner_id, revision, document, reason)
  values (saved_project.id, saved_project.owner_id, saved_project.revision, saved_project.document, p_reason);
  response := jsonb_build_object('projectId', saved_project.id, 'revision', saved_project.revision, 'state', saved_project.state, 'httpStatus', 200);
  insert into private.operation_receipts (owner_id, operation, idempotency_key, request_hash, status, response_ref)
  values (p_owner_id, operation_name, p_idempotency_key, p_request_hash, 'completed', response);
  return response;
end;
$$;
comment on function private.save_project(uuid, uuid, bigint, text, public.platform_preset, jsonb, public.project_version_reason, text, text) is '先重放操作回执，再以 CAS 保存项目、快照和同事务回执';
revoke execute on function private.save_project(uuid, uuid, bigint, text, public.platform_preset, jsonb, public.project_version_reason, text, text) from public, anon, authenticated;
grant execute on function private.save_project(uuid, uuid, bigint, text, public.platform_preset, jsonb, public.project_version_reason, text, text) to service_role;

create or replace function private.save_project(
  p_owner_id uuid, p_project_id uuid, p_expected_revision bigint, p_title text,
  p_platform public.platform_preset, p_document jsonb, p_reason public.project_version_reason default 'manual'
)
returns public.projects language plpgsql security definer set search_path = '' as $$
declare saved public.projects;
begin
  perform private.save_project(
    p_owner_id, p_project_id, p_expected_revision, p_title, p_platform, p_document, p_reason,
    'legacy:' || p_expected_revision::text || ':' || md5(p_document::text),
    md5(p_title || ':' || p_platform::text || ':' || p_document::text)
  );
  select * into saved from public.projects where id = p_project_id and owner_id = p_owner_id;
  return saved;
end;
$$;
comment on function private.save_project(uuid, uuid, bigint, text, public.platform_preset, jsonb, public.project_version_reason) is '兼容早期调用并以确定性回执键转入幂等保存事务';
revoke execute on function private.save_project(uuid, uuid, bigint, text, public.platform_preset, jsonb, public.project_version_reason) from public, anon, authenticated;
grant execute on function private.save_project(uuid, uuid, bigint, text, public.platform_preset, jsonb, public.project_version_reason) to service_role;

alter table public.jobs enable row level security;
alter table public.usage_accounts enable row level security;
alter table public.usage_ledger enable row level security;
alter table private.cost_budgets enable row level security;
alter table private.cost_reservations enable row level security;
alter table private.cost_attempts enable row level security;
alter table private.operation_receipts enable row level security;
alter table private.request_guards enable row level security;

revoke all on table public.jobs, public.usage_accounts, public.usage_ledger from anon, authenticated, service_role;
grant select on table public.jobs, public.usage_accounts, public.usage_ledger to authenticated;
grant select, insert, update, delete on table public.jobs, public.usage_accounts, public.usage_ledger to service_role;
revoke all on table private.cost_budgets, private.cost_reservations, private.cost_attempts, private.operation_receipts, private.request_guards from public, anon, authenticated, service_role;

drop policy if exists jobs_select_own_active on public.jobs;
create policy jobs_select_own_active on public.jobs for select to authenticated
using ((select auth.uid()) = owner_id and exists (select 1 from public.profiles where id = (select auth.uid()) and status = 'active'));
drop policy if exists usage_accounts_select_own_active on public.usage_accounts;
create policy usage_accounts_select_own_active on public.usage_accounts for select to authenticated
using ((select auth.uid()) = owner_id and exists (select 1 from public.profiles where id = (select auth.uid()) and status = 'active'));
drop policy if exists usage_ledger_select_own_active on public.usage_ledger;
create policy usage_ledger_select_own_active on public.usage_ledger for select to authenticated
using (exists (select 1 from public.usage_accounts where id = account_id and owner_id = (select auth.uid())));

-- source: supabase/definitions/ai-asset-budget.sql
create table if not exists private.ai_asset_reservations (
  asset_id uuid primary key references public.assets(id) on delete restrict,
  owner_id uuid not null references auth.users(id) on delete restrict,
  account_id uuid not null references public.usage_accounts(id) on delete restrict,
  environment text not null check (environment in ('development', 'preview', 'production')),
  period text not null check (period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  reserved_micro_usd bigint not null check (reserved_micro_usd >= 0),
  actual_micro_usd bigint,
  provider_operation_id text,
  state private.cost_reservation_state not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table private.ai_asset_reservations is 'AI 素材候选的用户额度与供应商成本原子预留';
comment on column private.ai_asset_reservations.asset_id is '候选素材标识与预留幂等键';
comment on column private.ai_asset_reservations.owner_id is '预留所有者标识';
comment on column private.ai_asset_reservations.account_id is '被预留的图片额度桶';
comment on column private.ai_asset_reservations.environment is '成本预算部署环境';
comment on column private.ai_asset_reservations.period is '成本预算 UTC 月份';
comment on column private.ai_asset_reservations.reserved_micro_usd is '预估供应商成本，单位微美元';
comment on column private.ai_asset_reservations.actual_micro_usd is '最终供应商成本，单位微美元';
comment on column private.ai_asset_reservations.provider_operation_id is '供应商任务对账标识';
comment on column private.ai_asset_reservations.state is '开放、结算或释放状态';
comment on column private.ai_asset_reservations.created_at is '创建时间（UTC）';
comment on column private.ai_asset_reservations.updated_at is '最近修改时间（UTC）';
alter table private.ai_asset_reservations enable row level security;
revoke all on private.ai_asset_reservations from public, anon, authenticated, service_role;

create or replace function public.server_create_ai_asset_candidate(
  p_asset_id uuid, p_owner_id uuid, p_kind public.asset_kind, p_object_key text,
  p_rights jsonb, p_environment text, p_reserved_micro_usd bigint
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare account public.usage_accounts; budget private.cost_budgets;
  period_key text := to_char(now() at time zone 'UTC', 'YYYY-MM');
begin
  perform pg_advisory_xact_lock(hashtextextended(p_owner_id::text || ':ai-asset:' || p_asset_id::text, 0));
  if exists (select 1 from public.assets where id = p_asset_id and owner_id = p_owner_id) then
    return jsonb_build_object('outcome', 'created', 'assetId', p_asset_id);
  end if;
  if p_kind not in ('ai_image', 'portrait') or jsonb_typeof(p_rights) <> 'object'
    or p_object_key <> p_owner_id::text || '/' || p_asset_id::text || '/pending.png'
    or not exists (select 1 from public.profiles where id = p_owner_id and status = 'active') then
    raise exception using errcode = '42501', message = 'AI candidate is not accessible';
  end if;
  select * into account from public.usage_accounts
  where owner_id = p_owner_id and resource = 'image' and now() >= period_start and now() < period_end
  order by period_start desc limit 1 for update;
  if account.id is null or account.granted - account.reserved - account.consumed < 1 then
    return jsonb_build_object('outcome', 'quota_exceeded');
  end if;
  select * into budget from private.cost_budgets
  where period = period_key and environment = p_environment for update;
  if budget.period is null or p_reserved_micro_usd < 0
    or budget.limit_micro_usd - budget.reserved_micro_usd - budget.spent_micro_usd < p_reserved_micro_usd then
    return jsonb_build_object('outcome', 'budget_exceeded');
  end if;
  insert into public.assets(id, owner_id, kind, purpose, bucket, object_key, mime, bytes, sha256, rights, state, library_retained)
  values(p_asset_id, p_owner_id, p_kind, 'media', 'assets', p_object_key, 'image/png', 0, repeat('0',64), p_rights, 'pending_upload', false);
  update public.usage_accounts set reserved = reserved + 1, updated_at = now() where id = account.id;
  insert into public.usage_ledger(account_id, event_key, kind, units)
  values(account.id, 'asset:' || p_asset_id::text || ':reserve', 'reserve', 1);
  update private.cost_budgets set reserved_micro_usd = reserved_micro_usd + p_reserved_micro_usd, updated_at = now()
  where period = period_key and environment = p_environment;
  insert into private.ai_asset_reservations(asset_id, owner_id, account_id, environment, period, reserved_micro_usd)
  values(p_asset_id, p_owner_id, account.id, p_environment, period_key, p_reserved_micro_usd);
  return jsonb_build_object('outcome', 'created', 'assetId', p_asset_id);
end $$;
comment on function public.server_create_ai_asset_candidate(uuid, uuid, public.asset_kind, text, jsonb, text, bigint) is '在同一事务中创建 AI 素材候选并预留图片额度及供应商成本';
revoke execute on function public.server_create_ai_asset_candidate(uuid, uuid, public.asset_kind, text, jsonb, text, bigint) from public, anon, authenticated;
grant execute on function public.server_create_ai_asset_candidate(uuid, uuid, public.asset_kind, text, jsonb, text, bigint) to service_role;

create or replace function public.server_finalize_ai_asset_candidate(
  p_asset_id uuid, p_owner_id uuid, p_succeeded boolean,
  p_provider_operation_id text, p_actual_micro_usd bigint
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare reservation private.ai_asset_reservations; expected_state public.asset_state;
begin
  select * into reservation from private.ai_asset_reservations
  where asset_id = p_asset_id and owner_id = p_owner_id for update;
  if reservation.asset_id is null then raise exception using errcode = '42501', message = 'AI candidate reservation unavailable'; end if;
  if reservation.state in ('settled', 'released') then
    return jsonb_build_object('outcome', reservation.state::text);
  end if;
  expected_state := case when p_succeeded then 'ready'::public.asset_state else 'failed'::public.asset_state end;
  if p_actual_micro_usd < 0 or not exists (
    select 1 from public.assets where id = p_asset_id and owner_id = p_owner_id and state = expected_state
  ) then raise exception using errcode = '22023', message = 'AI candidate terminal state mismatch'; end if;
  update public.usage_accounts set reserved = reserved - 1,
    consumed = consumed + case when p_succeeded then 1 else 0 end, updated_at = now()
  where id = reservation.account_id and reserved >= 1;
  if not found then raise exception using errcode = '22003', message = 'AI image quota invariant failed'; end if;
  insert into public.usage_ledger(account_id, event_key, kind, units)
  values(reservation.account_id, 'asset:' || p_asset_id::text || ':finalize',
    case when p_succeeded then 'settle'::public.usage_ledger_kind else 'release'::public.usage_ledger_kind end, 1);
  update private.cost_budgets set
    reserved_micro_usd = reserved_micro_usd - reservation.reserved_micro_usd,
    spent_micro_usd = spent_micro_usd + case when p_succeeded then p_actual_micro_usd else 0 end,
    updated_at = now()
  where period = reservation.period and environment = reservation.environment
    and reserved_micro_usd >= reservation.reserved_micro_usd;
  if not found then raise exception using errcode = '22003', message = 'AI image budget invariant failed'; end if;
  update private.ai_asset_reservations set
    actual_micro_usd = case when p_succeeded then p_actual_micro_usd else 0 end,
    provider_operation_id = p_provider_operation_id,
    state = case when p_succeeded then 'settled'::private.cost_reservation_state else 'released'::private.cost_reservation_state end,
    updated_at = now()
  where asset_id = p_asset_id;
  return jsonb_build_object('outcome', case when p_succeeded then 'settled' else 'released' end);
end $$;
comment on function public.server_finalize_ai_asset_candidate(uuid, uuid, boolean, text, bigint) is '按素材终态幂等结算图片额度与真实供应商成本，失败时释放全部预留';
revoke execute on function public.server_finalize_ai_asset_candidate(uuid, uuid, boolean, text, bigint) from public, anon, authenticated;
grant execute on function public.server_finalize_ai_asset_candidate(uuid, uuid, boolean, text, bigint) to service_role;

notify pgrst, 'reload schema';

-- source: supabase/definitions/deletion.sql
do $$
begin
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'deletion_scope') then
    create type public.deletion_scope as enum ('project', 'account');
  end if;
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'deletion_state') then
    create type public.deletion_state as enum ('pending', 'running', 'completed', 'failed');
  end if;
end
$$;

comment on type public.deletion_scope is '异步清理针对单个项目或整个账户';
comment on type public.deletion_state is '分阶段删除清理任务状态';

create table if not exists public.deletion_requests (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users (id) on delete restrict,
  scope public.deletion_scope not null,
  project_id uuid references public.projects (id) on delete restrict,
  state public.deletion_state not null default 'pending',
  error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint deletion_requests_target_check check ((scope = 'project' and project_id is not null) or (scope = 'account' and project_id is null)),
  constraint deletion_requests_completion_check check ((state = 'completed' and completed_at is not null) or (state <> 'completed' and completed_at is null))
);

comment on table public.deletion_requests is '权限立即切断后由后台执行的物理清理请求';
comment on column public.deletion_requests.id is '删除请求唯一标识';
comment on column public.deletion_requests.owner_id is '删除请求账户所有者';
comment on column public.deletion_requests.scope is '项目或账户删除范围';
comment on column public.deletion_requests.project_id is '项目删除时的目标项目';
comment on column public.deletion_requests.state is '后台清理执行状态';
comment on column public.deletion_requests.error_code is '可重试清理的安全错误码';
comment on column public.deletion_requests.created_at is '权限切断时间（UTC）';
comment on column public.deletion_requests.updated_at is '最近状态更新时间（UTC）';
comment on column public.deletion_requests.completed_at is '物理清理完成时间（UTC）';

create unique index if not exists deletion_requests_open_project_idx on public.deletion_requests (project_id) where project_id is not null and state in ('pending', 'running');
create unique index if not exists deletion_requests_open_account_idx on public.deletion_requests (owner_id) where scope = 'account' and state in ('pending', 'running');

create or replace function public.server_request_project_deletion(p_owner_id uuid, p_project_id uuid)
returns uuid language plpgsql security definer set search_path = '' as $$
declare request_id uuid;
begin
  update public.projects set state = 'deleting', deleted_at = coalesce(deleted_at, now()), updated_at = now()
  where id = p_project_id and owner_id = p_owner_id and state in ('draft', 'archived');
  if not found then raise exception using errcode = '42501', message = 'project is not accessible'; end if;
  update public.jobs set cancel_requested_at = coalesce(cancel_requested_at, now()), updated_at = now()
  where owner_id = p_owner_id and project_id = p_project_id and state not in ('succeeded', 'partial', 'failed', 'canceled');
  insert into public.deletion_requests (owner_id, scope, project_id) values (p_owner_id, 'project', p_project_id) returning id into request_id;
  return request_id;
end;
$$;
comment on function public.server_request_project_deletion(uuid, uuid) is '按所有者原子切断项目授权、请求运行中任务取消并登记后台清理';
revoke execute on function public.server_request_project_deletion(uuid, uuid) from public, anon, authenticated;
grant execute on function public.server_request_project_deletion(uuid, uuid) to service_role;

create or replace function public.server_request_account_deletion(p_owner_id uuid)
returns uuid language plpgsql security definer set search_path = '' as $$
declare request_id uuid;
begin
  update public.profiles set status = 'deleting' where id = p_owner_id and status = 'active';
  if not found then raise exception using errcode = '42501', message = 'account is not accessible'; end if;
  update public.projects set state = 'deleting', deleted_at = coalesce(deleted_at, now()), updated_at = now()
  where owner_id = p_owner_id and state in ('draft', 'archived');
  update public.jobs set cancel_requested_at = coalesce(cancel_requested_at, now()), updated_at = now()
  where owner_id = p_owner_id and state not in ('succeeded', 'partial', 'failed', 'canceled');
  insert into public.deletion_requests (owner_id, scope) values (p_owner_id, 'account') returning id into request_id;
  return request_id;
end;
$$;
comment on function public.server_request_account_deletion(uuid) is '原子切断账户及其项目授权、请求运行中任务取消并登记后台清理';
revoke execute on function public.server_request_account_deletion(uuid) from public, anon, authenticated;
grant execute on function public.server_request_account_deletion(uuid) to service_role;

create or replace function private.reject_deleted_owner_job_writeback()
returns trigger language plpgsql set search_path = '' as $$
begin
  if new.state in ('succeeded', 'partial') and old.state not in ('succeeded', 'partial') and (
    not exists (select 1 from public.profiles where id = new.owner_id and status = 'active')
    or (new.project_id is not null and not exists (select 1 from public.projects where id = new.project_id and owner_id = new.owner_id and state in ('draft', 'archived')))
  ) then
    raise exception using errcode = '55000', message = 'deleted owner cannot receive job results';
  end if;
  return new;
end;
$$;
comment on function private.reject_deleted_owner_job_writeback() is '阻止删除中的账户或项目接收成功任务结果';
revoke execute on function private.reject_deleted_owner_job_writeback() from public, anon, authenticated, service_role;
drop trigger if exists jobs_reject_deleted_owner_writeback on public.jobs;
create trigger jobs_reject_deleted_owner_writeback before update of state, result_ref on public.jobs for each row execute function private.reject_deleted_owner_job_writeback();
comment on trigger jobs_reject_deleted_owner_writeback on public.jobs is '任务成功写回前重新验证账户与项目仍可用';

alter table public.deletion_requests enable row level security;
revoke all on table public.deletion_requests from anon, authenticated, service_role;
grant select, insert, update, delete on table public.deletion_requests to service_role;

-- source: supabase/definitions/tool-outputs.sql
do $$
begin
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'tool_output_state') then
    create type public.tool_output_state as enum ('ready', 'expired', 'deleted');
  end if;
end
$$;
comment on type public.tool_output_state is '独立工具产物的授权生命周期';

create table if not exists public.tool_outputs (
  id uuid primary key,
  owner_id uuid not null references auth.users (id) on delete restrict,
  job_id uuid not null unique references public.jobs (id) on delete restrict,
  tool text not null check (tool in ('caption', 'linkedin-post', 'post-ideas', 'quote-card', 'infographic', 'portrait', 'carousel-to-video')),
  result jsonb not null check (jsonb_typeof(result) = 'object' and result ->> 'kind' in ('text', 'image', 'video')),
  asset_id uuid references public.assets (id) on delete restrict,
  context_project_id uuid references public.projects (id) on delete restrict,
  context_revision bigint,
  state public.tool_output_state not null default 'ready',
  expires_at timestamptz not null default (now() + interval '7 days'),
  created_at timestamptz not null default now(),
  constraint tool_outputs_context_check check ((context_project_id is null) = (context_revision is null)),
  constraint tool_outputs_asset_check check (
    (result ->> 'kind' = 'text' and asset_id is null)
    or (result ->> 'kind' in ('image', 'video') and asset_id is not null)
  )
);

comment on table public.tool_outputs is '不依附轮播项目的文本、单图或视频工具产物';
comment on column public.tool_outputs.id is '工具产物唯一标识';
comment on column public.tool_outputs.owner_id is '工具产物所有者标识';
comment on column public.tool_outputs.job_id is '生成该产物的唯一工具任务';
comment on column public.tool_outputs.tool is '七种注册工具之一';
comment on column public.tool_outputs.result is '符合 ToolResult 契约且不含原始输入或密钥的结果';
comment on column public.tool_outputs.asset_id is '图片或 MP4 私有对象的素材记录，文本结果为空';
comment on column public.tool_outputs.context_project_id is '用户明确选择上下文时的项目标识';
comment on column public.tool_outputs.context_revision is '用户明确选择上下文时固定的项目版本';
comment on column public.tool_outputs.state is '可下载、已过期或已删除状态';
comment on column public.tool_outputs.expires_at is '产物下载授权截止时间（UTC）';
comment on column public.tool_outputs.created_at is '产物创建时间（UTC）';

create index if not exists tool_outputs_owner_expiry_idx on public.tool_outputs (owner_id, state, expires_at);
create index if not exists tool_outputs_asset_idx on public.tool_outputs (asset_id) where asset_id is not null;

create or replace function public.server_register_tool_output(
  p_id uuid, p_owner_id uuid, p_job_id uuid, p_tool text, p_result jsonb,
  p_context_project_id uuid, p_context_revision bigint, p_expires_at timestamptz,
  p_asset_id uuid, p_object_key text, p_mime text, p_bytes bigint, p_sha256 text,
  p_width integer, p_height integer, p_duration_ms bigint
)
returns public.tool_outputs language plpgsql security definer set search_path = '' as $$
declare created public.tool_outputs; result_kind text;
begin
  result_kind := p_result ->> 'kind';
  if p_tool not in ('caption', 'linkedin-post', 'post-ideas', 'quote-card', 'infographic', 'portrait', 'carousel-to-video')
    or result_kind is null or result_kind not in ('text', 'image', 'video') or p_expires_at <= now()
    or (p_tool in ('caption', 'linkedin-post', 'post-ideas') and result_kind <> 'text')
    or (p_tool in ('quote-card', 'infographic', 'portrait') and result_kind <> 'image')
    or (p_tool = 'carousel-to-video' and result_kind <> 'video') then
    raise exception using errcode = '22023', message = 'invalid tool output';
  end if;
  if not exists (select 1 from public.profiles where id = p_owner_id and status = 'active')
    or not exists (select 1 from public.jobs where id = p_job_id and owner_id = p_owner_id and kind = 'tool') then
    raise exception using errcode = '42501', message = 'tool job is not accessible';
  end if;
  if (p_context_project_id is null) <> (p_context_revision is null) or (
    p_context_project_id is not null and not exists (
      select 1 from public.projects where id = p_context_project_id and owner_id = p_owner_id
      and revision = p_context_revision and state in ('draft', 'archived')
    )
  ) then raise exception using errcode = '42501', message = 'tool context is not accessible'; end if;
  if result_kind = 'text' then
    if p_asset_id is not null or p_object_key is not null then raise exception using errcode = '22023', message = 'text tool output cannot have an object'; end if;
  else
    if p_asset_id is null or p_object_key is null or p_object_key !~ ('^' || p_owner_id::text || '/' || p_job_id::text || '/' || p_id::text || '/')
      or p_bytes <= 0 or p_sha256 !~ '^[0-9a-f]{64}$'
      or (result_kind = 'image' and (p_mime not in ('image/png', 'image/jpeg') or p_width is null or p_height is null))
      or (result_kind = 'video' and (p_mime <> 'video/mp4' or p_duration_ms is null)) then
      raise exception using errcode = '22023', message = 'invalid tool output object';
    end if;
    insert into public.assets (id, owner_id, kind, purpose, bucket, object_key, mime, bytes, sha256, width, height, duration_ms, rights, state)
    values (p_asset_id, p_owner_id, 'derived', 'tool_output', 'exports', p_object_key, p_mime, p_bytes, p_sha256, p_width, p_height, p_duration_ms, jsonb_build_object('tool', p_tool, 'jobId', p_job_id), 'ready');
  end if;
  insert into public.tool_outputs (id, owner_id, job_id, tool, result, asset_id, context_project_id, context_revision, expires_at)
  values (p_id, p_owner_id, p_job_id, p_tool, p_result, p_asset_id, p_context_project_id, p_context_revision, p_expires_at)
  returning * into created;
  return created;
end;
$$;
comment on function public.server_register_tool_output(uuid, uuid, uuid, text, jsonb, uuid, bigint, timestamptz, uuid, text, text, bigint, text, integer, integer, bigint) is '按 owner、工具任务和显式项目版本原子登记独立工具结果及可选私有对象';
revoke execute on function public.server_register_tool_output(uuid, uuid, uuid, text, jsonb, uuid, bigint, timestamptz, uuid, text, text, bigint, text, integer, integer, bigint) from public, anon, authenticated;
grant execute on function public.server_register_tool_output(uuid, uuid, uuid, text, jsonb, uuid, bigint, timestamptz, uuid, text, text, bigint, text, integer, integer, bigint) to service_role;

alter table public.tool_outputs enable row level security;
revoke all on table public.tool_outputs from anon, authenticated, service_role;
grant select on table public.tool_outputs to authenticated;
grant select, insert, update, delete on table public.tool_outputs to service_role;
drop policy if exists tool_outputs_select_own_available on public.tool_outputs;
create policy tool_outputs_select_own_available on public.tool_outputs for select to authenticated using (
  (select auth.uid()) = owner_id and state = 'ready' and expires_at > now()
  and exists (select 1 from public.profiles where id = (select auth.uid()) and status = 'active')
);

drop policy if exists storage_download_owned_tool_outputs on storage.objects;
create policy storage_download_owned_tool_outputs on storage.objects for select to authenticated using (
  bucket_id = 'exports' and exists (
    select 1 from public.assets join public.tool_outputs on tool_outputs.asset_id = assets.id
    where assets.bucket = 'exports' and assets.object_key = storage.objects.name
      and assets.owner_id = (select auth.uid()) and assets.purpose = 'tool_output' and assets.state = 'ready'
      and tool_outputs.owner_id = (select auth.uid()) and tool_outputs.state = 'ready' and tool_outputs.expires_at > now()
      and exists (select 1 from public.profiles where id = (select auth.uid()) and status = 'active')
  )
);
